version: 2

registries:
  tilleggsstonader-libs:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/tilleggsstonader-libs
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}

updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  groups:
    backend:
      patterns:
        - "*"
  open-pull-requests-limit: 10
  registries:
    - tilleggsstonader-libs
  ignore:
    - dependency-name: "io.mockk:mockk"
      versions: [ "1.13.13" ]

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "08:00"
  commit-message:
    prefix: "[docker] "