apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: tilleggsstonader-sak-alerts
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  groups:
    - name: alerts
      rules:
        - alert: Feilede iverksettinger
          expr: andel_tilkjent_ytelse_iverksetting_status{status="FEILET"} > 0
          annotations:
            consequence: Vi har mottatt FEILET-status fra hel-ved ved iverksetting
            action: "Sjekk logger for å finne iverksetting-id som har feilet og kontakt hel-ved"
          labels:
            namespace: tilleggsstonader
            severity: critical
        - alert: Iverksettinger uten status
          expr: andel_tilkjent_ytelse_iverksetting_status{status="IKKE_MOTTATT_STATUS_FRA_HELVED"} > 0
          annotations:
            consequence: Iverksettinger uten mottatt status fra hel-ved
            action: "Sjekk logger for å finne iverksetting-id ikke har mottatt status og kontakt hel-ved"
          labels:
            namespace: tilleggsstonader
            severity: critical
