apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: utbetaling.v1
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact,delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 3
    retentionBytes: -1
    retentionHours: 336
  acl:
    - team: tilleggsstonader
      application: tilleggsstonader-sak
      access: readwrite
    - team: helved
      application: peisschtappern
      access: read
    - team: helved
      application: abetal
      access: read
