apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-tilleggsstonader-dvh-behandling
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2016
  acl:
    - team: tilleggsstonader
      application: tilleggsstonader-sak
      access: readwrite
    - team: tilleggsstonader
      application: tilleggsstonader-klage
      access: readwrite
    - team: ptsak
      application: pt-sak-tilleggsstonader
      access: read