CREATE TABLE FAGSAK_UTBETALING_ID
(
    UTBETALING_ID         VARCHAR(25) NOT NULL PRIMARY KEY,
    FAGSAK_ID  UUID        NOT NULL REFERENCES fagsak (id),
    TYPE_ANDEL VARCHAR(50) NOT NULL
);

create unique index on FAGSAK_UTBETALING_ID (fagsak_id, type_andel);

