UPDATE fagsak
SET stonadstype = 'REISE_OPPSTART_AVSLUTNING_HJEMREISE_TSO'
WHERE stonadstype = 'STØTTE_TIL_REISE_OPPSTART_AVSLUTNING_HJEMREISE_TSO';

UPDATE fagsak
SET stonadstype = 'REISE_OPPSTART_AVSLUTNING_HJEMREISE_TSR'
WHERE stonadstype = 'STØTTE_TIL_REISE_OPPSTART_AVSLUTNING_HJEMREISE_TSR';