ALTER TABLE vilkar
    ADD COLUMN sha VARCHAR NOT NULL DEFAULT '';
ALTER TABLE vilkar_periode
    ADD COLUMN sha VARCHAR NOT NULL DEFAULT '';
ALTER TABLE stonadsperiode
    ADD COLUMN sha VARCHAR NOT NULL DEFAULT '';

ALTER TABLE vilkar
    ALTER COLUMN sha DROP DEFAULT;
ALTER TABLE vilkar_periode
    ALTER COLUMN sha DROP DEFAULT;
ALTER TABLE stonadsperiode
    ALTER COLUMN sha DROP DEFAULT;
