name: action pin refresh

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: action-pin-refresh
  cancel-in-progress: false

jobs:
  refresh-action-pins:
    uses: navikt/tilleggsstonader/.github/workflows/action-pin-refresh.yml@main
