name: Deploy unleash api-token for prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy unleash api-token
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/unleash-apitoken-prod.yaml
          PRINT_PAYLOAD: true