name: Deploy Kafka topics to dev-gcp
on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy-kafka-topic:
    name: Deploy Kafka topics to dev-gcp
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: "\
            .nais/topics/statistikk-dvh-behandling/topic-dev.yaml,\
            .nais/topics/utbetaling.v1/topic-dev.yaml"