name: Deploy Kafka topics to prod-gcp
on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy-kafka-topic:
    name: Deploy Kafka topics to prod-gcp
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: "\
            .nais/topics/statistikk-dvh-behandling/topic-prod.yaml,\
            .nais/topics/utbetaling.v1/topic-prod.yaml"
