name: digestabot

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

jobs:
  digestabot:
    name: Update image digests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: navikt/digestabot@3233d68167c867ef8227c5dfde7a30f2a0e10af0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: tilleggsstonader
