name: Submit dependency graph
on:
  push:
    branches:
      - main
    paths:
      - "**.gradle.kts"
      - "gradle.properties"
jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit
      - name: Run a build, generating the dependency graph snapshot which will be submitted
        run: ./gradlew build